# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gabagool < Formula
  desc "Local-first AI development proxy and context engine"
  homepage "https://github.com/Kobie-Bendalak/Gabagool"
  version "3.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.1/gabagool_3.2.1_darwin_x86_64.tar.gz"
      sha256 "a1dd484b8f8bac0236b7adbc403f6454b563488cbd066441c1a6bbe3feff9f75"

      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.1/gabagool_3.2.1_darwin_arm64.tar.gz"
      sha256 "42fe5019813ec4cecc0019acfcf5901fc849e89d804b86662c4c73b791df0130"

      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.1/gabagool_3.2.1_linux_x86_64.tar.gz"
      sha256 "fe58e7e88c569504ecbe4dadd57a9234cdf8c9da17ada6df4d1ef3142dd450d7"
      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.1/gabagool_3.2.1_linux_arm64.tar.gz"
      sha256 "78d17048ad729264c6e3b91cdf894ebd79b8fb0b0eaa01d9bbacde186bb0fcef"
      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Gabagool needs Docker Desktop (or another docker-compose-capable daemon)
      running to start its services.

      First run:
        gabagool init       # detects Keychain OAuth, writes ~/.gabagool/env, pulls images
        gabagool start      # bring the stack up
        gabagool doctor     # verify everything is wired

      Auto-start at login (optional):
        gabagool service install

      Point your IDE at the proxy:
        export ANTHROPIC_BASE_URL=http://localhost:7878
    EOS
  end

  test do
    system bin/"gabagool", "--help"
  end
end
