# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gabagool < Formula
  desc "Local-first AI development proxy and context engine"
  homepage "https://github.com/Kobie-Bendalak/Gabagool"
  version "3.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.6/gabagool_3.2.6_darwin_x86_64.tar.gz"
      sha256 "113ccf028d01053bb2cc92f823ffa748b8cd5088ad16ad7f7a99641fc2457c40"

      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.6/gabagool_3.2.6_darwin_arm64.tar.gz"
      sha256 "f8e8e747a02d2bb2cf586b9fad0daa76f7347a1b93b014a423ef5548b9cfa60b"

      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.6/gabagool_3.2.6_linux_x86_64.tar.gz"
      sha256 "6fde51a4ace09891c8a5564fdefe85a9e5143928e17f88733d20797f98b8e70e"
      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.2.6/gabagool_3.2.6_linux_arm64.tar.gz"
      sha256 "80b5e241bbf384b97217b8d1c80f6551d547ea1eb31ffbf91ccb87866870636a"
      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Gabagool needs Docker Desktop (or another docker-compose-capable daemon)
      running to start its services.

      First run:
        gabagool init       # detects Keychain OAuth, writes ~/.gabagool/env, pulls images
        gabagool start      # bring the stack up
        gabagool doctor     # verify everything is wired

      Auto-start at login (optional):
        gabagool service install

      Point your IDE at the proxy:
        export ANTHROPIC_BASE_URL=http://localhost:7878
    EOS
  end

  test do
    system bin/"gabagool", "--help"
  end
end
