# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gabagool < Formula
  desc "Local-first AI development proxy and context engine"
  homepage "https://github.com/Kobie-Bendalak/Gabagool"
  version "3.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.3.3/gabagool_3.3.3_darwin_x86_64.tar.gz"
      sha256 "8620ee83843076058e06a4d42f733105db2a5726ff9f77f5a01beb566b2c31e6"

      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.3.3/gabagool_3.3.3_darwin_arm64.tar.gz"
      sha256 "f261f18c2f673a03306265f902d6ccea373399df1fc4e76185f9967a8ad0bffd"

      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.3.3/gabagool_3.3.3_linux_x86_64.tar.gz"
      sha256 "fbc5a468bbbd831200ffa1a8c166bf58f6d9ee777576b005230785e24a75a066"
      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/gabagool-dist/releases/download/v3.3.3/gabagool_3.3.3_linux_arm64.tar.gz"
      sha256 "a7c3d7e9adcbb9f96b250e3bae59033f1dec106fb7f46a91779856697c4959e9"
      define_method(:install) do
        bin.install "gabagool"
        generate_completions_from_executable(bin/"gabagool", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
      end
    end
  end

  def caveats
    <<~EOS
      Gabagool needs Docker Desktop (or another docker-compose-capable daemon)
      running to start its services.

      First run:
        gabagool init       # detects Keychain OAuth, writes ~/.gabagool/env, pulls images
        gabagool start      # bring the stack up
        gabagool doctor     # verify everything is wired

      Auto-start at login (optional):
        gabagool service install

      Point your IDE at the proxy:
        export ANTHROPIC_BASE_URL=http://localhost:7878
    EOS
  end

  test do
    system bin/"gabagool", "--help"
  end
end
